import { Agent, Task } from './types';

export const AGENTS: Agent[] = [
  // Engineering
  { id: 'backend-architect', name: 'Backend Architect', emoji: '🏗️', division: 'Engineering', description: 'Designs and builds scalable backend systems and APIs' },
  { id: 'code-reviewer', name: 'Code Reviewer', emoji: '👁️', division: 'Engineering', description: 'Reviews code for quality, security, and best practices' },
  { id: 'database-optimizer', name: 'Database Optimizer', emoji: '🗄️', division: 'Engineering', description: 'Tunes database schemas, queries, and performance' },
  { id: 'devops-automator', name: 'DevOps Automator', emoji: '⚙️', division: 'Engineering', description: 'Automates CI/CD pipelines and infrastructure provisioning' },
  { id: 'embedded-firmware-engineer', name: 'Embedded Firmware Engineer', emoji: '🔩', division: 'Engineering', description: 'Develops firmware for embedded systems and hardware' },
  { id: 'feishu-integration-developer', name: 'Feishu Integration Developer', emoji: '🔗', division: 'Engineering', description: 'Builds integrations with Feishu enterprise collaboration tools' },
  { id: 'frontend-developer', name: 'Frontend Developer', emoji: '🖥️', division: 'Engineering', description: 'Builds responsive, performant web UIs with modern frameworks' },
  { id: 'git-workflow-master', name: 'Git Workflow Master', emoji: '🌿', division: 'Engineering', description: 'Manages branching strategies and version control workflows' },
  { id: 'infrastructure-maintainer', name: 'Infrastructure Maintainer', emoji: '🏢', division: 'Engineering', description: 'Keeps cloud infrastructure healthy, patched, and optimized' },
  { id: 'lsp-index-engineer', name: 'LSP/Index Engineer', emoji: '🔎', division: 'Engineering', description: 'Builds language server tooling and code intelligence indexes' },
  { id: 'macos-spatial-metal-engineer', name: 'macOS Spatial/Metal Engineer', emoji: '🍎', division: 'Engineering', description: 'Develops GPU-accelerated graphics with Apple Metal APIs' },
  { id: 'mobile-app-builder', name: 'Mobile App Builder', emoji: '📲', division: 'Engineering', description: 'Develops cross-platform mobile applications for iOS and Android' },
  { id: 'senior-developer', name: 'Senior Developer', emoji: '💎', division: 'Engineering', description: 'Full-stack development with deep architectural ownership' },
  { id: 'software-architect', name: 'Software Architect', emoji: '🏛️', division: 'Engineering', description: 'Defines system design patterns and technical strategy' },
  { id: 'solidity-smart-contract-engineer', name: 'Solidity Smart Contract Engineer', emoji: '⛓️', division: 'Engineering', description: 'Authors and audits smart contracts on EVM-compatible chains' },
  { id: 'sre-site-reliability-engineer', name: 'SRE', emoji: '🛡️', division: 'Engineering', description: 'Ensures uptime, reliability, and observability at scale' },
  { id: 'terminal-integration-specialist', name: 'Terminal Integration Specialist', emoji: '🖥️', division: 'Engineering', description: 'Builds CLI tools and terminal-native developer experiences' },
  { id: 'visionos-spatial-engineer', name: 'visionOS Spatial Engineer', emoji: '🥽', division: 'Engineering', description: 'Creates immersive spatial experiences for Apple Vision Pro' },
  { id: 'wechat-mini-program-developer', name: 'WeChat Mini Program Developer', emoji: '💬', division: 'Engineering', description: 'Develops mini-programs within the WeChat super-app ecosystem' },
  { id: 'xr-immersive-developer', name: 'XR Immersive Developer', emoji: '🌐', division: 'Engineering', description: 'Builds WebXR and mixed-reality experiences for the open web' },

  // Marketing
  { id: 'ad-creative-strategist', name: 'Ad Creative Strategist', emoji: '✍️', division: 'Marketing', description: 'Crafts high-converting ad creative across all channels' },
  { id: 'app-store-optimizer', name: 'App Store Optimizer', emoji: '📱', division: 'Marketing', description: 'Optimizes App Store listings for discoverability and conversions' },
  { id: 'baidu-seo-specialist', name: 'Baidu SEO Specialist', emoji: '🇨🇳', division: 'Marketing', description: 'Drives organic visibility on Baidu for China market audiences' },
  { id: 'bilibili-content-strategist', name: 'Bilibili Content Strategist', emoji: '🎬', division: 'Marketing', description: 'Grows brand presence on Bilibili through video content strategy' },
  { id: 'brand-guardian', name: 'Brand Guardian', emoji: '🎨', division: 'Marketing', description: 'Maintains brand consistency and identity across all touchpoints' },
  { id: 'carousel-growth-engine', name: 'Carousel Growth Engine', emoji: '🎠', division: 'Marketing', description: 'Produces viral carousel content for social media growth' },
  { id: 'content-creator', name: 'Content Creator', emoji: '✍️', division: 'Marketing', description: 'Produces compelling content that educates, entertains, and converts' },
  { id: 'developer-advocate', name: 'Developer Advocate', emoji: '🗣️', division: 'Marketing', description: 'Builds developer community and produces technical content' },
  { id: 'douyin-strategist', name: 'Douyin Strategist', emoji: '🎵', division: 'Marketing', description: 'Executes short-video strategy for Douyin to drive brand growth' },
  { id: 'growth-hacker', name: 'Growth Hacker', emoji: '🚀', division: 'Marketing', description: 'Identifies and exploits growth loops across the funnel' },
  { id: 'instagram-curator', name: 'Instagram Curator', emoji: '📸', division: 'Marketing', description: 'Curates Instagram feeds and stories for aesthetic and engagement' },
  { id: 'kuaishou-strategist', name: 'Kuaishou Strategist', emoji: '🎥', division: 'Marketing', description: 'Drives community growth on Kuaishou short-video platform' },
  { id: 'linkedin-content-creator', name: 'LinkedIn Content Creator', emoji: '💼', division: 'Marketing', description: 'Builds thought leadership and pipeline through LinkedIn content' },
  { id: 'paid-media-auditor', name: 'Paid Media Auditor', emoji: '📋', division: 'Marketing', description: 'Audits ad spend for waste and optimization opportunities' },
  { id: 'paid-social-strategist', name: 'Paid Social Strategist', emoji: '📱', division: 'Marketing', description: 'Manages paid social campaigns across Meta, TikTok, and LinkedIn' },
  { id: 'podcast-strategist', name: 'Podcast Strategist', emoji: '🎧', division: 'Marketing', description: 'Plans and promotes podcast content for audience growth' },
  { id: 'ppc-campaign-strategist', name: 'PPC Campaign Strategist', emoji: '💰', division: 'Marketing', description: 'Manages pay-per-click campaigns on Google and Bing' },
  { id: 'private-domain-operator', name: 'Private Domain Operator', emoji: '🔒', division: 'Marketing', description: 'Grows and monetizes owned audiences through WeChat and private channels' },
  { id: 'programmatic-display-buyer', name: 'Programmatic & Display Buyer', emoji: '📺', division: 'Marketing', description: 'Executes programmatic ad buying for reach and retargeting' },
  { id: 'reddit-community-builder', name: 'Reddit Community Builder', emoji: '💬', division: 'Marketing', description: 'Builds authentic brand presence and community on Reddit' },
  { id: 'search-query-analyst', name: 'Search Query Analyst', emoji: '🔍', division: 'Marketing', description: 'Analyzes search queries to surface intent and keyword opportunities' },
  { id: 'seo-specialist', name: 'SEO Specialist', emoji: '🔍', division: 'Marketing', description: 'Drives organic search growth through on-page and off-page SEO' },
  { id: 'short-video-editing-coach', name: 'Short-Video Editing Coach', emoji: '🎬', division: 'Marketing', description: 'Coaches teams on hook-driven short-form video editing techniques' },
  { id: 'social-media-strategist', name: 'Social Media Strategist', emoji: '📣', division: 'Marketing', description: 'Develops unified social media strategy across all platforms' },
  { id: 'tiktok-strategist', name: 'TikTok Strategist', emoji: '🎵', division: 'Marketing', description: 'Creates viral TikTok content strategy and influencer campaigns' },
  { id: 'tracking-measurement-specialist', name: 'Tracking & Measurement Specialist', emoji: '📡', division: 'Marketing', description: 'Implements tracking infrastructure for accurate attribution' },
  { id: 'trend-researcher', name: 'Trend Researcher', emoji: '🔭', division: 'Marketing', description: 'Monitors emerging trends and surfaces actionable market insights' },
  { id: 'twitter-engager', name: 'Twitter Engager', emoji: '🐦', division: 'Marketing', description: 'Builds brand voice and community on Twitter/X' },
  { id: 'visual-storyteller', name: 'Visual Storyteller', emoji: '🎬', division: 'Marketing', description: 'Crafts compelling visual narratives for brand and product' },
  { id: 'wechat-official-account-manager', name: 'WeChat Official Account Manager', emoji: '📱', division: 'Marketing', description: 'Manages WeChat official account content and subscriber growth' },
  { id: 'weibo-strategist', name: 'Weibo Strategist', emoji: '🔥', division: 'Marketing', description: 'Executes Weibo content strategy for Chinese social media presence' },
  { id: 'xiaohongshu-specialist', name: 'Xiaohongshu Specialist', emoji: '🌸', division: 'Marketing', description: 'Grows brand presence on Xiaohongshu (Little Red Book)' },
  { id: 'zhihu-strategist', name: 'Zhihu Strategist', emoji: '🧠', division: 'Marketing', description: 'Builds authority and trust on Zhihu through expert Q&A content' },

  // Sales & Revenue
  { id: 'account-strategist', name: 'Account Strategist', emoji: '🗺️', division: 'Sales & Revenue', description: 'Develops account expansion strategies to grow existing revenue' },
  { id: 'china-e-commerce-operator', name: 'China E-Commerce Operator', emoji: '🛒', division: 'Sales & Revenue', description: 'Manages e-commerce operations across Tmall, JD, and Taobao' },
  { id: 'cross-border-e-commerce-specialist', name: 'Cross-Border E-Commerce Specialist', emoji: '🌏', division: 'Sales & Revenue', description: 'Enables cross-border commerce with logistics and compliance expertise' },
  { id: 'deal-strategist', name: 'Deal Strategist', emoji: '♟️', division: 'Sales & Revenue', description: 'Qualifies and structures deals to maximize win rates' },
  { id: 'discovery-coach', name: 'Discovery Coach', emoji: '🔍', division: 'Sales & Revenue', description: 'Coaches reps on running effective discovery conversations' },
  { id: 'government-digital-presales-consultant', name: 'Government Digital Presales Consultant', emoji: '🏛️', division: 'Sales & Revenue', description: 'Navigates government procurement for digital transformation deals' },
  { id: 'livestream-commerce-coach', name: 'Livestream Commerce Coach', emoji: '🎙️', division: 'Sales & Revenue', description: 'Coaches live selling strategies for e-commerce conversion' },
  { id: 'outbound-strategist', name: 'Outbound Strategist', emoji: '🎯', division: 'Sales & Revenue', description: 'Builds outbound sequences and prospecting playbooks' },
  { id: 'pipeline-analyst', name: 'Pipeline Analyst', emoji: '📊', division: 'Sales & Revenue', description: 'Forecasts pipeline health and identifies revenue risks' },
  { id: 'proposal-strategist', name: 'Proposal Strategist', emoji: '🏹', division: 'Sales & Revenue', description: 'Writes winning proposals and RFP responses' },
  { id: 'sales-coach', name: 'Sales Coach', emoji: '🏋️', division: 'Sales & Revenue', description: 'Uplevels sales team performance through coaching and training' },
  { id: 'sales-engineer', name: 'Sales Engineer', emoji: '🛠️', division: 'Sales & Revenue', description: 'Provides technical validation and demos during sales cycles' },

  // Data & Analytics
  { id: 'analytics-reporter', name: 'Analytics Reporter', emoji: '📊', division: 'Data & Analytics', description: 'Produces business intelligence reports and dashboards' },
  { id: 'data-consolidation-agent', name: 'Data Consolidation Agent', emoji: '🗄️', division: 'Data & Analytics', description: 'Aggregates and normalizes data from disparate sources' },
  { id: 'data-engineer', name: 'Data Engineer', emoji: '🔧', division: 'Data & Analytics', description: 'Builds pipelines and data infrastructure for analytics' },
  { id: 'identity-graph-operator', name: 'Identity Graph Operator', emoji: '🕸️', division: 'Data & Analytics', description: 'Resolves entities and builds identity graphs across data sources' },
  { id: 'sales-data-extraction-agent', name: 'Sales Data Extraction Agent', emoji: '📊', division: 'Data & Analytics', description: 'Extracts and cleans sales data for pipeline reporting' },

  // Operations
  { id: 'compliance-auditor', name: 'Compliance Auditor', emoji: '📋', division: 'Operations', description: 'Audits processes for regulatory and policy compliance' },
  { id: 'corporate-training-designer', name: 'Corporate Training Designer', emoji: '📚', division: 'Operations', description: 'Designs learning programs and training materials for teams' },
  { id: 'document-generator', name: 'Document Generator', emoji: '📄', division: 'Operations', description: 'Automates creation of documents, contracts, and templates' },
  { id: 'executive-summary-generator', name: 'Executive Summary Generator', emoji: '📝', division: 'Operations', description: 'Distills complex information into crisp executive summaries' },
  { id: 'healthcare-marketing-compliance-specialist', name: 'Healthcare Marketing Compliance Specialist', emoji: '⚕️', division: 'Operations', description: 'Ensures healthcare marketing meets FDA and compliance standards' },
  { id: 'incident-response-commander', name: 'Incident Response Commander', emoji: '🚨', division: 'Operations', description: 'Commands incident response for critical production issues' },
  { id: 'jira-workflow-steward', name: 'Jira Workflow Steward', emoji: '📋', division: 'Operations', description: 'Optimizes Jira workflows and project management processes' },
  { id: 'legal-compliance-checker', name: 'Legal Compliance Checker', emoji: '⚖️', division: 'Operations', description: 'Checks content and contracts for legal compliance issues' },
  { id: 'project-shepherd', name: 'Project Shepherd', emoji: '🐑', division: 'Operations', description: 'Keeps projects on track through coordination and accountability' },
  { id: 'recruitment-specialist', name: 'Recruitment Specialist', emoji: '🎯', division: 'Operations', description: 'Sources and screens candidates for open roles' },
  { id: 'report-distribution-agent', name: 'Report Distribution Agent', emoji: '📤', division: 'Operations', description: 'Automates report generation and delivery to stakeholders' },
  { id: 'senior-project-manager', name: 'Senior Project Manager', emoji: '📝', division: 'Operations', description: 'Manages complex cross-functional projects end-to-end' },
  { id: 'sprint-prioritizer', name: 'Sprint Prioritizer', emoji: '🎯', division: 'Operations', description: 'Facilitates sprint planning and backlog prioritization' },
  { id: 'studio-operations', name: 'Studio Operations', emoji: '🏭', division: 'Operations', description: 'Manages day-to-day studio workflows and resource allocation' },
  { id: 'studio-producer', name: 'Studio Producer', emoji: '🎬', division: 'Operations', description: 'Produces creative projects from brief to delivery' },
  { id: 'study-abroad-advisor', name: 'Study Abroad Advisor', emoji: '🎓', division: 'Operations', description: 'Advises students on international study and application processes' },
  { id: 'supply-chain-strategist', name: 'Supply Chain Strategist', emoji: '🔗', division: 'Operations', description: 'Optimizes supply chain for resilience and cost efficiency' },
  { id: 'support-responder', name: 'Support Responder', emoji: '💬', division: 'Operations', description: 'Handles customer support tickets with speed and empathy' },
  { id: 'technical-writer', name: 'Technical Writer', emoji: '📚', division: 'Operations', description: 'Produces clear technical documentation for developers and users' },
  { id: 'tool-evaluator', name: 'Tool Evaluator', emoji: '🔧', division: 'Operations', description: 'Assesses and recommends tools for team productivity' },
  { id: 'workflow-optimizer', name: 'Workflow Optimizer', emoji: '⚡', division: 'Operations', description: 'Redesigns workflows to eliminate waste and increase throughput' },
  { id: 'zk-steward', name: 'ZK Steward', emoji: '🗃️', division: 'Operations', description: 'Manages and curates organizational knowledge and documentation' },

  // Finance
  { id: 'accounts-payable-agent', name: 'Accounts Payable Agent', emoji: '💸', division: 'Finance', description: 'Processes invoices and manages vendor payment workflows' },
  { id: 'finance-tracker', name: 'Finance Tracker', emoji: '💰', division: 'Finance', description: 'Tracks budgets, forecasts, and financial performance' },

  // AI Infrastructure
  { id: 'agentic-identity-trust-architect', name: 'Agentic Identity & Trust Architect', emoji: '🔐', division: 'AI Infrastructure', description: 'Designs identity and trust systems for multi-agent pipelines' },
  { id: 'agents-orchestrator', name: 'Agents Orchestrator', emoji: '🎛️', division: 'AI Infrastructure', description: 'Orchestrates complex multi-agent pipelines and workflows' },
  { id: 'ai-engineer', name: 'AI Engineer', emoji: '🤖', division: 'AI Infrastructure', description: 'Architects and deploys production ML systems and AI pipelines' },
  { id: 'autonomous-optimization-architect', name: 'Autonomous Optimization Architect', emoji: '⚡', division: 'AI Infrastructure', description: 'Builds self-optimizing systems that improve without human input' },
  { id: 'mcp-builder', name: 'MCP Builder', emoji: '🔌', division: 'AI Infrastructure', description: 'Builds Model Context Protocol servers and tool integrations' },

  // Product
  { id: 'behavioral-nudge-engine', name: 'Behavioral Nudge Engine', emoji: '🧠', division: 'Product', description: 'Designs behavioral nudges to improve user activation and retention' },
  { id: 'cultural-intelligence-strategist', name: 'Cultural Intelligence Strategist', emoji: '🌍', division: 'Product', description: 'Ensures products are culturally adapted for global markets' },
  { id: 'experiment-tracker', name: 'Experiment Tracker', emoji: '🧪', division: 'Product', description: 'Designs and tracks A/B experiments for product optimization' },
  { id: 'feedback-synthesizer', name: 'Feedback Synthesizer', emoji: '🔍', division: 'Product', description: 'Synthesizes user feedback into actionable product insights' },
  { id: 'image-prompt-engineer', name: 'Image Prompt Engineer', emoji: '📷', division: 'Product', description: 'Engineers prompts for AI image generation at production quality' },
  { id: 'inclusive-visuals-specialist', name: 'Inclusive Visuals Specialist', emoji: '🌈', division: 'Product', description: 'Creates accessible and inclusive visual content standards' },
  { id: 'rapid-prototyper', name: 'Rapid Prototyper', emoji: '⚡', division: 'Product', description: 'Builds fast prototypes to validate product ideas quickly' },
  { id: 'ui-designer', name: 'UI Designer', emoji: '🎨', division: 'Product', description: 'Designs beautiful, functional interfaces with precision' },
  { id: 'ux-architect', name: 'UX Architect', emoji: '📐', division: 'Product', description: 'Designs information architecture and UX systems at scale' },
  { id: 'ux-researcher', name: 'UX Researcher', emoji: '🔬', division: 'Product', description: 'Conducts user research to inform product direction' },
  { id: 'whimsy-injector', name: 'Whimsy Injector', emoji: '✨', division: 'Product', description: 'Adds delightful micro-interactions and personality to products' },
  { id: 'xr-cockpit-interaction-specialist', name: 'XR Cockpit Interaction Specialist', emoji: '🕹️', division: 'Product', description: 'Designs spatial UI for XR cockpit and industrial interfaces' },
  { id: 'xr-interface-architect', name: 'XR Interface Architect', emoji: '🫧', division: 'Product', description: 'Architects spatial interfaces for extended reality environments' },

  // Security
  { id: 'blockchain-security-auditor', name: 'Blockchain Security Auditor', emoji: '🛡️', division: 'Security', description: 'Audits smart contracts and blockchain systems for vulnerabilities' },
  { id: 'security-engineer', name: 'Security Engineer', emoji: '🔒', division: 'Security', description: 'Designs and implements security architecture across all systems' },
  { id: 'threat-detection-engineer', name: 'Threat Detection Engineer', emoji: '🎯', division: 'Security', description: 'Builds threat detection systems and incident response tooling' },

  // QA & Testing
  { id: 'accessibility-auditor', name: 'Accessibility Auditor', emoji: '♿', division: 'QA & Testing', description: 'Audits products for WCAG accessibility compliance' },
  { id: 'api-tester', name: 'API Tester', emoji: '🔌', division: 'QA & Testing', description: 'Validates API contracts, performance, and edge cases' },
  { id: 'evidence-collector', name: 'Evidence Collector', emoji: '📸', division: 'QA & Testing', description: 'Captures visual evidence and screenshots for QA validation' },
  { id: 'model-qa-specialist', name: 'Model QA Specialist', emoji: '🔬', division: 'QA & Testing', description: 'Tests and validates ML model outputs for quality and safety' },
  { id: 'performance-benchmarker', name: 'Performance Benchmarker', emoji: '⏱️', division: 'QA & Testing', description: 'Benchmarks system performance and identifies bottlenecks' },
  { id: 'reality-checker', name: 'Reality Checker', emoji: '🧐', division: 'QA & Testing', description: 'Validates production readiness with real-world scenario testing' },
  { id: 'test-results-analyzer', name: 'Test Results Analyzer', emoji: '📋', division: 'QA & Testing', description: 'Analyzes test results to identify patterns and failure trends' },

  // Gaming
  { id: 'game-audio-engineer', name: 'Game Audio Engineer', emoji: '🎵', division: 'Gaming', description: 'Designs and implements audio systems and soundscapes for games' },
  { id: 'game-designer', name: 'Game Designer', emoji: '🎮', division: 'Gaming', description: 'Designs game mechanics, systems, and player experiences' },
  { id: 'godot-gameplay-scripter', name: 'Godot Gameplay Scripter', emoji: '🎯', division: 'Gaming', description: 'Scripts gameplay systems and mechanics in Godot Engine' },
  { id: 'godot-multiplayer-engineer', name: 'Godot Multiplayer Engineer', emoji: '🌐', division: 'Gaming', description: 'Builds multiplayer netcode and server architecture in Godot' },
  { id: 'godot-shader-developer', name: 'Godot Shader Developer', emoji: '💎', division: 'Gaming', description: 'Creates visual effects and shaders with Godot shader language' },
  { id: 'level-designer', name: 'Level Designer', emoji: '🗺️', division: 'Gaming', description: 'Designs game levels that deliver compelling player experiences' },
  { id: 'narrative-designer', name: 'Narrative Designer', emoji: '📖', division: 'Gaming', description: 'Crafts interactive narratives, dialogue, and story systems' },
  { id: 'roblox-avatar-creator', name: 'Roblox Avatar Creator', emoji: '👤', division: 'Gaming', description: 'Creates UGC avatar items and accessories for Roblox marketplace' },
  { id: 'roblox-experience-designer', name: 'Roblox Experience Designer', emoji: '🎪', division: 'Gaming', description: 'Designs and builds engaging Roblox game experiences' },
  { id: 'roblox-systems-scripter', name: 'Roblox Systems Scripter', emoji: '🔧', division: 'Gaming', description: 'Scripting game systems in Lua for Roblox platform' },
  { id: 'technical-artist', name: 'Technical Artist', emoji: '🎨', division: 'Gaming', description: 'Bridges art and engineering with shaders, tools, and pipelines' },
  { id: 'unity-architect', name: 'Unity Architect', emoji: '🏛️', division: 'Gaming', description: 'Architects scalable Unity game projects and engine systems' },
  { id: 'unity-editor-tool-developer', name: 'Unity Editor Tool Developer', emoji: '🛠️', division: 'Gaming', description: 'Builds custom Unity Editor tools to accelerate development' },
  { id: 'unity-multiplayer-engineer', name: 'Unity Multiplayer Engineer', emoji: '🔗', division: 'Gaming', description: 'Implements multiplayer systems using Unity Netcode and services' },
  { id: 'unity-shader-graph-artist', name: 'Unity Shader Graph Artist', emoji: '✨', division: 'Gaming', description: 'Creates stunning visual effects with Unity Shader Graph' },
  { id: 'unreal-multiplayer-architect', name: 'Unreal Multiplayer Architect', emoji: '🌐', division: 'Gaming', description: 'Architects multiplayer systems with Unreal Engine networking' },
  { id: 'unreal-systems-engineer', name: 'Unreal Systems Engineer', emoji: '⚙️', division: 'Gaming', description: 'Builds game systems and gameplay code in Unreal Engine' },
  { id: 'unreal-technical-artist', name: 'Unreal Technical Artist', emoji: '🎨', division: 'Gaming', description: 'Creates VFX, materials, and technical art pipelines in Unreal' },
  { id: 'unreal-world-builder', name: 'Unreal World Builder', emoji: '🌍', division: 'Gaming', description: 'Constructs detailed open worlds and environments in Unreal Engine' },
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-001',
    title: 'Redesign landing page hero section',
    description: 'Update the hero section with new brand visuals, updated copy, and a refreshed CTA flow. Needs to hit 90+ Lighthouse score.',
    status: 'in_progress',
    priority: 'high',
    agent_id: 'frontend-developer',
    agent_name: 'Frontend Developer',
    agent_emoji: '🖥️',
    created_at: daysAgo(3),
    updated_at: hoursAgo(2),
    logs: [
      { id: 'l1', timestamp: daysAgo(3), message: 'Task created and assigned to Frontend Developer', type: 'info' },
      { id: 'l2', timestamp: daysAgo(2), message: 'Started wireframe exploration in Figma', type: 'info' },
      { id: 'l3', timestamp: hoursAgo(8), message: 'Implemented responsive grid layout', type: 'success' },
      { id: 'l4', timestamp: hoursAgo(2), message: 'Running Lighthouse audit, score currently at 87', type: 'warning' },
    ],
  },
  {
    id: 'task-002',
    title: 'Write Q1 SEO content brief',
    description: 'Research and compile target keywords for Q1. Identify 20 high-intent topics with search volume data and competition scores.',
    status: 'review',
    priority: 'medium',
    agent_id: 'seo-specialist',
    agent_name: 'SEO Specialist',
    agent_emoji: '🔍',
    created_at: daysAgo(5),
    updated_at: hoursAgo(6),
    output: '# Q1 SEO Content Brief\n\nTop 20 target keywords identified with avg. monthly search volume of 12,400. Primary cluster: "AI workflow automation" (8,100/mo, KD 42)...',
    logs: [
      { id: 'l1', timestamp: daysAgo(5), message: 'Task created', type: 'info' },
      { id: 'l2', timestamp: daysAgo(4), message: 'Keyword research started using Ahrefs + SemRush', type: 'info' },
      { id: 'l3', timestamp: daysAgo(1), message: 'Brief draft completed and submitted for review', type: 'success' },
    ],
  },
  {
    id: 'task-003',
    title: 'Set up CI/CD pipeline for staging',
    description: 'Implement GitHub Actions workflow to auto-deploy to staging on every PR merge to main. Include automated tests and Slack notifications.',
    status: 'done',
    priority: 'urgent',
    agent_id: 'devops-automator',
    agent_name: 'DevOps Automator',
    agent_emoji: '⚙️',
    created_at: daysAgo(7),
    updated_at: hoursAgo(24),
    completed_at: hoursAgo(24),
    output: 'Pipeline live at .github/workflows/staging.yml. Avg deploy time: 4m 12s. All tests passing. Slack webhook configured for #deploys channel.',
    logs: [
      { id: 'l1', timestamp: daysAgo(7), message: 'Task created with URGENT priority', type: 'info' },
      { id: 'l2', timestamp: daysAgo(6), message: 'Scaffolded GitHub Actions workflow', type: 'info' },
      { id: 'l3', timestamp: daysAgo(5), message: 'Integrated test runner and coverage reports', type: 'success' },
      { id: 'l4', timestamp: hoursAgo(26), message: 'Pipeline failing on Docker build step - investigating', type: 'error' },
      { id: 'l5', timestamp: hoursAgo(25), message: 'Fixed: Docker layer cache was stale', type: 'success' },
      { id: 'l6', timestamp: hoursAgo(24), message: 'All checks passing. Marking complete.', type: 'success' },
    ],
  },
  {
    id: 'task-004',
    title: 'Audit database query performance',
    description: 'Profile slow queries on the reporting dashboard. Target: all queries under 200ms. Focus on the user_events and sessions tables.',
    status: 'todo',
    priority: 'high',
    agent_id: 'database-optimizer',
    agent_name: 'Database Optimizer',
    agent_emoji: '🗄️',
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
    logs: [
      { id: 'l1', timestamp: daysAgo(1), message: 'Task created', type: 'info' },
    ],
  },
  {
    id: 'task-005',
    title: 'Create TikTok content calendar for March',
    description: 'Plan 30 days of TikTok content aligned with product launches and seasonal moments. Include hook formulas, trending audio suggestions.',
    status: 'in_progress',
    priority: 'medium',
    agent_id: 'tiktok-strategist',
    agent_name: 'TikTok Strategist',
    agent_emoji: '🎵',
    created_at: daysAgo(2),
    updated_at: hoursAgo(4),
    logs: [
      { id: 'l1', timestamp: daysAgo(2), message: 'Task created', type: 'info' },
      { id: 'l2', timestamp: daysAgo(1), message: 'Competitor analysis complete - identified 12 trending formats', type: 'success' },
      { id: 'l3', timestamp: hoursAgo(4), message: 'Calendar 60% complete, working on week 3-4', type: 'info' },
    ],
  },
  {
    id: 'task-006',
    title: 'Write API documentation for v2 endpoints',
    description: 'Document all new v2 REST endpoints with OpenAPI spec. Include request/response examples, auth requirements, and rate limits.',
    status: 'backlog',
    priority: 'low',
    agent_id: 'technical-writer',
    agent_name: 'Technical Writer',
    agent_emoji: '📚',
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
    logs: [
      { id: 'l1', timestamp: daysAgo(4), message: 'Task created and added to backlog', type: 'info' },
    ],
  },
  {
    id: 'task-007',
    title: 'Security audit of authentication flow',
    description: 'Full penetration test of the auth system. Check for session fixation, token expiry, brute force protection, and OAuth implementation.',
    status: 'backlog',
    priority: 'urgent',
    agent_id: 'security-engineer',
    agent_name: 'Security Engineer',
    agent_emoji: '🔒',
    created_at: hoursAgo(12),
    updated_at: hoursAgo(12),
    logs: [
      { id: 'l1', timestamp: hoursAgo(12), message: 'Task created with URGENT priority', type: 'info' },
    ],
  },
  {
    id: 'task-008',
    title: 'Build MCP server for Notion integration',
    description: 'Create an MCP server that exposes Notion workspace as tools. Agents should be able to read pages, create docs, and query databases.',
    status: 'in_progress',
    priority: 'high',
    agent_id: 'mcp-builder',
    agent_name: 'MCP Builder',
    agent_emoji: '🔌',
    created_at: daysAgo(3),
    updated_at: hoursAgo(1),
    logs: [
      { id: 'l1', timestamp: daysAgo(3), message: 'Task created', type: 'info' },
      { id: 'l2', timestamp: daysAgo(2), message: 'Notion API auth flow implemented', type: 'success' },
      { id: 'l3', timestamp: daysAgo(1), message: 'Read tools working, starting write operations', type: 'info' },
      { id: 'l4', timestamp: hoursAgo(1), message: 'Database query tool complete - testing edge cases', type: 'info' },
    ],
  },
  {
    id: 'task-009',
    title: 'Quarterly pipeline analysis report',
    description: 'Analyze Q1 pipeline data. Segment by source, stage, ACV, and close rate. Identify top 3 bottlenecks and recommend actions.',
    status: 'review',
    priority: 'high',
    agent_id: 'pipeline-analyst',
    agent_name: 'Pipeline Analyst',
    agent_emoji: '📊',
    created_at: daysAgo(4),
    updated_at: hoursAgo(18),
    output: '## Q1 Pipeline Analysis\n\nTotal pipeline: $4.2M across 87 opportunities. Stage 3 (Technical Validation) showing 34% drop-off vs 22% industry average...',
    logs: [
      { id: 'l1', timestamp: daysAgo(4), message: 'Task created', type: 'info' },
      { id: 'l2', timestamp: daysAgo(3), message: 'CRM data extraction complete', type: 'success' },
      { id: 'l3', timestamp: daysAgo(1), message: 'Analysis draft submitted for CEO review', type: 'info' },
    ],
  },
  {
    id: 'task-010',
    title: 'A/B test new onboarding flow',
    description: 'Design and launch A/B test comparing current 5-step onboarding vs new 3-step flow. Primary metric: day-7 activation rate.',
    status: 'todo',
    priority: 'high',
    agent_id: 'experiment-tracker',
    agent_name: 'Experiment Tracker',
    agent_emoji: '🧪',
    created_at: hoursAgo(6),
    updated_at: hoursAgo(6),
    logs: [
      { id: 'l1', timestamp: hoursAgo(6), message: 'Task created', type: 'info' },
    ],
  },
  {
    id: 'task-011',
    title: 'Synthesize user interviews for feature X',
    description: 'Review 24 user interview recordings and synthesize key themes, pain points, and opportunities for the upcoming feature roadmap.',
    status: 'done',
    priority: 'medium',
    agent_id: 'ux-researcher',
    agent_name: 'UX Researcher',
    agent_emoji: '🔬',
    created_at: daysAgo(8),
    updated_at: daysAgo(2),
    completed_at: daysAgo(2),
    output: '# User Research Synthesis - Feature X\n\n**Key Themes (n=24)**\n1. Complexity of current workflow (19/24 mentioned)\n2. Lack of status visibility (17/24)\n3. Desire for bulk actions (15/24)\n\n**Recommended Priority:** Address workflow complexity first...',
    logs: [
      { id: 'l1', timestamp: daysAgo(8), message: 'Task created', type: 'info' },
      { id: 'l2', timestamp: daysAgo(6), message: 'Reviewed 12 of 24 interviews', type: 'info' },
      { id: 'l3', timestamp: daysAgo(4), message: 'All interviews reviewed, affinity mapping complete', type: 'success' },
      { id: 'l4', timestamp: daysAgo(2), message: 'Synthesis report delivered', type: 'success' },
    ],
  },
  {
    id: 'task-012',
    title: 'Configure Xiaohongshu brand account',
    description: 'Set up official Xiaohongshu brand presence. Create 10 seed posts, establish tone of voice, and outline first 30 days of content.',
    status: 'backlog',
    priority: 'medium',
    agent_id: 'xiaohongshu-specialist',
    agent_name: 'Xiaohongshu Specialist',
    agent_emoji: '🌸',
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
    logs: [
      { id: 'l1', timestamp: hoursAgo(3), message: 'Task created', type: 'info' },
    ],
  },
];
